/*
 *  File: CardsSchema.js
 *  Type: Schema
 *  Generated by: Mongoose-Fixture (v0.4.1)
 *
 *
 */

var mongoose = require('mongoose');


var CardSchema = new mongoose.Schema({
  number: Number,
  name: String,
  suit: String,
  has: Array
});

mongoose.model('Card', CardSchema);


